version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
